###  - Test appending bias to 2d matrix and then Test Time complexity for flattening and reshaping np.arrays.

In [9]:
import numpy as np

In [18]:
z = np.zeros((3,3))
z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
y = np.append(z, 1)
print(y, z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.] [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


###  - Also test results of finnegan's backprop against matrix form from Dolhansky.